development:
  adapter: postgresql
  encoding: unicode
  database: papuche_dev
  pool: 5
  username: postgres
  password: marion

test:
  adapter: postgresql
  encoding: unicode
  database: papuche_test
  pool: 5
  username: postgres
  password: marion