development:
  adapter: postgresql
  encoding: unicode
  database: papuche
  pool: 5
  username: papuche
  password: foo

test:
  adapter: postgresql
  encoding: unicode
  database: papuche
  pool: 5
  username: papuche
  password: foo