default: &default
  adapter: postgresql
  encoding: unicode
  database: papuche_development
  pool: 5
  username: postgres
  password: marion

development:
  adapter: postgresql
  encoding: unicode
  database: papuche_development
  pool: 5
  username: postgres
  password: marion

test:
  adapter: postgresql
  encoding: unicode
  database: papuche_test
  pool: 5
  username: postgres
  password: marion

production:
  adapter: postgresql
  encoding: unicode
  database: papuche_production
  pool: 5
  username: postgres
  password: marion